config/routes.rb
CaveJohnsonFoundation::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/auth/:provider/callback" => "sessions#create", :as => :auth_callback
  match "/auth/failure" => "sessions#failure", :as => :auth_failure
  match "/logout" => "sessions#destroy", :as => :logout

  resources :apps do
    resources :features do
      resources :donations
    end
  end


  root to: 'apps#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :name, :description, :url, :logo, :screenshot
  has_many :features
  has_attached_file :logo, :styles => { :medium => "238x238>",:thumb => "100x100>"}
  has_attached_file :screenshot, :styles => { :medium => "238x238>",:thumb => "100x100>", :large => "500x500>"}
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :amount, :feature, :user, :feature_id, :user_id

  belongs_to :user
  belongs_to :feature

  validates_presence_of :amount

  scope :latest, limit(5).order("updated_at desc").includes(:feature => :app).includes(:user)
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  attr_accessible :app, :user, :name, :description, :current_amount, :app_id, :user_id

  belongs_to :app
  belongs_to :user
  has_many :donations

  validates_presence_of :name
  validates_presence_of :description

  state_machine initial: :suggested do
    state :suggested
    state :accepted
    state :financied
    event :accept do
      transition suggested: :financied, if: lambda {|feature| feature.succeeded?}
      transition suggested: :accepted
    end
    event :goal_reached do
      transition accepted: :financied
    end
  end

  def receive donation
    donations << donation
    goal_reached if succeeded?
  end

  def current_amount
    donations.map(&:amount).reduce(&:+) || 0
  end

  def succeeded?
    goal <= current_amount if goal.present? && current_amount.present?
  end
end

app/models/feature_observer.rb
class FeatureObserver < ActiveRecord::Observer
  def after_transition(feature, transition)
    if feature.succeeded?
      feature.donations.map(&:user).each do |user|
        NotificationsMailer.delay.feature_succeeded(feature.id, user.id)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :donations
  has_many :features

  def self.find_or_create_with_omniauth(auth)
    user = self.find_or_create_by_provider_and_uid(auth["provider"], auth["uid"])
    user.assign_attributes({
      :name => auth["info"]["name"], 
      :email => auth["info"]["email"], 
      :photo_url => auth["info"]["image"], 
      :access_token => auth["credentials"]["token"]}, 
      :without_protection => true)
    user.save(:validate => false)
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :user_signed_in?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !current_user.nil?
  end

  def authenticate!
    user_signed_in? || redirect_to((request.env["HTTP_REFERER"].blank?) ? root_path : :back, :notice => "You need to be logged in!")
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    @apps = App.scoped
    @latest_donations = Donation.latest
  end

  def show
    @app = App.find(params[:id])
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate!, only: :create

  def new
    app = App.find params[:app_id]
    feature = Feature.new(app: app)
    @donation = Donation.new(feature: feature, user: current_user)
  end

  def create
    @feature = Feature.find(params[:feature_id])
    @donation = Donation.new(params[:donation])
    @feature.receive @donation

    respond_to do |format|
      if @donation.save && @feature.save
        NotificationsMailer.delay.donated(@donation.id, current_user.id)
        format.html { redirect_to app_feature_path(@feature.app, @feature), notice: "Donation offered!" }
        format.json { head :no_content }
      else
        format.html { render action: 'new', controller: 'donations' }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_filter :authenticate!, only: :create

  def new
    app = App.find params[:app_id]
    @feature = Feature.new(app: app, user: current_user)
  end

  def show
    @feature = Feature.find(params[:id])
  end

  def create
    @feature = Feature.new(params[:feature])
    respond_to do |format|
      if @feature.save
        format.html { redirect_to new_app_feature_donation_path(@feature.app, @feature), notice: 'Feature suggested! Now offer some money to it!' }
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_or_create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url
  end

  def failure
    redirect_to root_url, :alert => 'Could not authenticate, sorry.'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "User logged out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find session[:user_id]
  end
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/views/apps/index.haml
- content_for :scripts do
  :plain
    <script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

#home-content
  =c :home_content, default: "Suggest features you want to Apps you ♥"

#feature-list
  %h2 Latest donations
  - @latest_donations.each do |donation|
    %a{ href: app_feature_path(donation.feature.app, donation.feature) }
      .feature-suggestion
        .app-icon.logo.logo-big
          %img{:src => donation.feature.app.logo.url(:thumb)}
        .feature-details
          %p.feature-title
            %strong
              = donation.feature.name
            with
            %strong
              = number_to_currency donation.amount
          %p
            suggested by
            %strong
              = donation.user.name
            = image_tag donation.user.photo_url, class: "user-avatar"
            for
            = number_to_currency donation.amount
          %p.date
            = "#{time_ago_in_words donation.created_at} ago"


#app-list
  %h2 Apps
  %ul
    - @apps.each do |app|
      %li.app
        .logo.logo-xbig
          = link_to image_tag(app.logo.url(:thumb)), app
        %h3
          = link_to app.name, app

app/views/apps/show.haml
#app
  %section{:role => "header"}
    .logo.logo-big
      = image_tag @app.logo.url(:thumb)
    %h2.title
      = @app.name
      = link_to @app.url
  %section{:role => "content"}
    .description
      .screen-shot
        = image_tag @app.screenshot.url(:large)
      .text
        = @app.description

    .features
      %h3.title Desired Features

      .btn.btn-success.btn-large
        = link_to 'Suggest new feature now!', new_app_feature_path(@app)

      %ul
      - @app.features.each do |feature|
        %li.feature
          = link_to feature.name, app_feature_path(@app, feature)

app/views/donations/new.haml
:javascript
  $(function(){ $("#amount").maskMoney(); })

=c :donation_text, default: "Placeholder for donation page"
%h1 Offer your donation for this idea!
= form_for([@donation.feature.app, @donation.feature, @donation], url: app_feature_donations_path, method: 'post') do |f|
  - if @donation.errors.any?
    #error_explanation
      %h2
        = pluralize(@donation.errors.count, 'error') 
        Not saved!
      %ul
        - @donation.errors.full_messages.each do |msg|
          %li
            = msg
  .field
    = f.label :amount
    = f.text_field :amount, id: 'amount'
    = f.submit 'Donate!'

  = f.hidden_field :feature_id
  = f.hidden_field :user_id

app/views/features/_accepted.haml
= "Current Amount: #{number_to_currency feature.current_amount}"
%br
= "Goal: #{number_to_currency feature.goal}"
%br
Accepted feature

app/views/features/_financied.haml
This feature has been financied! \o/
= "Donated so far: #{number_to_currency feature.current_amount}"

app/views/features/_form.haml
= form_for([@feature.app, @feature]) do |f|
  - if @feature.errors.any?
    #error_explanation
      %h2
        = pluralize(@feature.errors.count, 'error') 
        Not saved!
      %ul
        - @feature.errors.full_messages.each do |msg|
          %li
            = msg
  .field
    = f.label 'Name your Feature'
    = f.text_field :name

  .field
    = f.label :description
    = f.text_area :description

  = f.hidden_field :user_id
  = f.hidden_field :app_id

  .actions
    = f.submit 'Create feature', {class: "btn"}

app/views/features/_suggested.haml
= "Current Amount: #{number_to_currency feature.current_amount}"
%br
Suggested feature

app/views/features/new.haml
#add-feature
  %h2
    = "Awesome Feature for #{@feature.app.name}"
  = render 'form'

app/views/features/show.haml
#top
  #app-logo
    = image_tag @feature.app.logo.url
  %h1
    %stong
      = @feature.name
  
  %h2 
    %span for
    %storng
      = @feature.app.name

#feature-state
  .status
    = render @feature.state, feature: @feature

#user-info
  #user-pic
    %img{ src: "#{@feature.user.photo_url}" }
  #user-name
    Suggested by 
    %strong= "#{@feature.user.name}"

%article.feature-description
  %p
    = simple_format @feature.description

#donate.btn.btn-large.btn-success
  = link_to 'Donate!', new_app_feature_donation_path(@feature.app, @feature)

app/views/layouts/application.html.haml
/utf-8
!!! 5
%html{:lang => "pt"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "keywords", :content => ""}
    %meta{:name => "description", :content => ""}

    %title= yield(:title) + "Featurette"

    %link{:href => "/favicon.png", :rel => "shortcut icon"}
    = yield(:header_tags)

    = stylesheet_link_tag "application", :type => nil, :media => "all"
    = javascript_include_tag "application", :type => nil
    = csrf_meta_tags

    /[if lt IE 9]
      %script{:src => "http://html5shim.googlecode.com/svn/trunk/html5.js"}

    :plain
      <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'XXXXX-XXXX']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      </script>

  %body{:id => controller.controller_name}
    %header
      .wrap
        #logo<
          %h1
            = link_to "Featurette", root_url

        #masthead
          - if current_user
            .user
              .picture
                %img{ src: "#{current_user.photo_url}" }
              .name
                = current_user.name
              .logout
                = link_to "Logout", logout_path
          - else
            .login-button
              = link_to "Access with Facebook", "/auth/facebook", :id => "facebook-connect"

    .messages
      - if notice
        %p.notice
          = notice
      - if alert
        %p.alert
          = alert

    .wrap
      .content

      %section{:role => "main"}
        = yield

      - if content_for?(:sidebar)
        %aside
          = yield(:sidebar)
      %footer
        %p
        #twitter
          %a.twitter-share-button{"data-hashtags" => "featurette,StartupDevRumble", "data-size" => "large", "data-text" => "Featurette - Suggest features you want to the Apps you love!", "data-url" => "http://199.231.86.38/", :href => "https://twitter.com/share"} Tweet
          :javascript
            !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
        %p
          = "Copyright &copy; 2012 Cave Johnson Foundation".html_safe